//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArTrax472.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public int CustomerId { get; set; }
        public int EquipId { get; set; }
        public int LoadTypeId { get; set; }
        public int TruckId { get; set; }
        public bool AddToInvoice { get; set; }
        public int ProductId { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string TicketNumber { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public bool IsLineTaxable { get; set; }
        public string UserField1 { get; set; }
    
        public virtual Equip Equip { get; set; }
        public virtual LoadType LoadType { get; set; }
        public virtual Product Product { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
